#
# Created by JFormDesigner on Sat Jan 03 20:59:39 CET 2026
#

ItsqRefExportsPanel.button2.text=text
ItsqRefExportsPhasePanel.button1.text=text
ItsqRefExportsPhasePanel.button2.text=text
ITSQViewPanel.button1.text=text
ITSQViewPanel.button2.text=text
